version: '3'

services:
  survey_db:
    image: postgres:latest
    container_name: survey_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - surveynetwork

  survey_web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - survey_db
    env_file:
      - .env
    networks:
      - surveynetwork

networks:
  surveynetwork:
    driver: bridge

volumes:
  pgdata:
