version: '3'

services:
  survey_web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - backend_rpgnetwork
    volumes:
      - /home/shalini/Dataset/Synthetic-User-Study:/datasets/
networks:
  backend_rpgnetwork:
    external: true

volumes:
  pgdata:
