# Generated by Django 5.0.4 on 2024-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_right_answer',
            field=models.BooleanField(default=False),
        ),
    ]
