# Generated by Django 5.0.4 on 2024-05-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_useranswer_is_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
